finance/urls.py
from django.urls import path

from .import views

app_name = 'finance'

urlpatterns = [
	
	#path('home/', name='home'),
	
	#Accounting urls
	#path('accounting/', name='accounting'),
	
		#Transactions urls
	path('accounting/transactions/', views.TransactionArchiveView.as_view(), name='transactions_list'),
	path('accounting/transactions/<int:year>/', views.TransactionYearArchiveView.as_view(), name='archive_year'),
	path('accounting/transactions/<int:year>/<int:month>/', views.TransactionMonthArchiveView.as_view(), name='archive_month'),
	path('accounting/transactions/<int:year>/<int:month>/<int:day>/', views.TransactionDayArchiveView.as_view(), name='archive_day'),
	path('accounting/transactions/create/', views.TransactionCreateView.as_view(), name='transaction_create'),
	path('accounting/transactions/id/<int:pk>/', views.TransactionDetailView.as_view(), name='transaction_detail'),
	path('accounting/transactions/id/<int:pk>/edit/', views.TransactionEditView.as_view(), name='transaction_edit'),
	path('accounting/transactions/id/<int:pk>/delete/', views.TransactionDeleteView.as_view(), name='transaction_delete'),
	
		#Account urls
	path('accounting/accounts/', views.AccountsListView.as_view(), name='accounts_list'),
	path('accounting/accounts/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
	path('accounting/accounts/create/', views.AccountCreateView.as_view(), name='account_create'),
	path('accounting/accounts/<int:pk>/edit/', views.AccountEditView.as_view(), name='account_edit'),
	path('accounting/accounts/<int:pk>/delete/', views.AccountDeleteView.as_view(), name='account_delete'),
	
		#Currencies urls
	path('accounting/currencies/', views.CurrenciesListView.as_view(), name='currencies_list'),
	path('accounting/currencies/create/', views.CurrencyCreateView.as_view(), name='currency_create'),
	path('accounting/currencies/<int:pk>/edit/', views.CurrencyEditView.as_view(), name='currency_edit'),
	path('accounting/currencies/<int:pk>/delete/', views.CurrencyDeleteView.as_view(), name='currency_delete'),
	
		#Types urls
	path('accounting/types/', views.TypesListView.as_view(), name='types_list'),
	path('accounting/types/create/', views.TypeCreateView.as_view(), name='type_create'),
	path('accounting/types/<int:pk>/edit/', views.TypeEditView.as_view(), name='type_edit'),
	path('accounting/types/<int:pk>/delete/', views.TypeDeleteView.as_view(), name='type_delete'),
	
		#Category urls
	path('accounting/categories/', views.CategoriesListView.as_view(), name='categories_list'),
	path('accounting/categories/create/', views.CategoryCreateView.as_view(), name='category_create'),
	path('accounting/categories/<int:pk>/edit/', views.CategoryEditView.as_view(), name='category_edit'),
	path('accounting/categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
	
		#Subcategories urls
	path('accounting/subcategories/', views.SubcategoriesListView.as_view(), name='subcategories_list'),
	path('accounting/subcategories/create/', views.SubcategoryCreateView.as_view(), name='subcategory_create'),
	path('accounting/subcategories/<int:pk>/edit/', views.SubcategoryEditView.as_view(), name='subcategory_edit'),
	path('accounting/subcategories/<int:pk>/delete/', views.SubcategoryDeleteView.as_view(), name='subcategory_delete'),
	
		#Places urls
	path('accounting/places/', views.PlacesListView.as_view(), name='places_list'),
	path('accounting/places/create/', views.PlaceCreateView.as_view(), name='place_create'),
	path('accounting/places/<int:pk>/edit/', views.PlaceEditView.as_view(), name='place_edit'),
	path('accounting/places/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='place_delete'),
	
	#Statistics urls
	#path('statistics', name='statistics'),
	
	#Planning urls
	#path('planning/spending/category/add', views.plan_spending_category_add, name='plan_spending_category_add'),
    #path('planning/spending/category/edit'), views.plan_spending_category_edit, name='plan_spending_category_add'),
]

finance/views.py
from decimal import *
from django import forms
from django.forms import formset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import dates
from .models import Transaction, Account, Currency, Type, Category, Subcategory, Place, AccountError

# Create your views here.

#Transactions views
	
class TransactionArchiveView(dates.ArchiveIndexView):
	model = Transaction
	date_field = 'create_datetime'
	template_name = 'finance/transaction/transaction_archive.html'
	
class TransactionYearArchiveView(dates.YearArchiveView):
	model = Transaction
	date_field = 'create_datetime'
	make_object_list = True
	template_name = 'finance/transaction/transaction_archive_year.html'
	
class TransactionMonthArchiveView(dates.MonthArchiveView):
	model = Transaction
	date_field = 'create_datetime'
	month_format = '%m'
	template_name = 'finance/transaction/transaction_archive_month.html'
	allow_future = True
	
class TransactionDayArchiveView(dates.DayArchiveView):
	model = Transaction
	date_field = 'create_datetime'
	month_format = '%m'
	template_name = 'finance/transaction/transaction_archive_day.html'
	allow_future = True
	
class TransactionDetailView(generic.DetailView):
	model = Transaction
	template_name = 'finance/transaction/transaction_detail.html'
	
class TransactionCreateView(generic.CreateView):
	model = Transaction
	fields = '__all__'
	template_name = 'finance/transaction/transaction_create.html'
	
	def form_valid(self, form):
		if not form.cleaned_data.get('from_account') and not form.cleaned_data.get('on_account'):
			raise forms.ValidationError('Вкажіть хоча б один рахунок для проведення трансакції')
		return super().form_valid(form)
	
	def post(self, request, *args, **kwargs):
		amount = Decimal(request.POST.get('amount', ''))
		currency = Currency.objects.get(pk=request.POST.get('currency', ''))
		from_account = request.POST.get('from_account', '')
		on_account = request.POST.get('on_account', '')
		if from_account:
			ad = Account.objects.get(pk=from_account)
			ad.decrease(amount, currency)
			ad.save()
		if on_account:
			ai = Account.objects.get(pk=on_account)
			ai.increase(amount, currency)
			ai.save()
		return super().post(request, *args, **kwargs)
	
class TransactionEditView(generic.UpdateView):
	model = Transaction
	fields = '__all__'
	template_name = 'finance/transaction/transaction_edit.html'
	
	def form_valid(self, form):
		if not form.cleaned_data.get('from_account') and not form.cleaned_data.get('on_account'):
			raise forms.ValidationError('Вкажіть хоча б один рахунок для проведення трансакції')
		return super().form_valid(form)
	
	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		transaction = Transaction.objects.get(pk=self.object.pk)
		post_amount = Decimal(request.POST.get('amount'))
		post_currency = Currency.objects.get(pk=request.POST.get('currency'))
		
		if transaction.from_account and request.POST.get('from_account'):
			post_from_account_id = request.POST.get('from_account')
			post_from_account = Account.objects.get(pk=post_from_account_id)
			transaction_from_account = Account.objects.get(pk=transaction.from_account.id)
			
			if transaction.from_account.id == int(post_from_account_id):
				amount_diff_d = post_amount - transaction.amount
				transaction_from_account.decrease(amount_diff_d, post_currency)
				post_from_account.decrease(amount_diff_d, post_currency)
				
			else:
				transaction_from_account.increase(transaction.amount, transaction.currency)
				post_from_account.decrease(post_amount, post_currency)
				
		else:
			if transaction.from_account:
				transaction_from_account = Account.objects.get(pk=transaction.from_account.id)
				transaction_from_account.increase(transaction.amount, transaction.currency)
			
			if request.POST.get('from_account'):
				post_from_account = Account.objects.get(pk=request.POST.get('from_account'))
				post_from_account.decrease(post_amount, post_currency)
			
			
		if transaction.on_account and request.POST.get('on_account'):
			post_on_account_id = request.POST.get('on_account')
			transaction_on_account = Account.objects.get(pk=transaction.on_account.id)
			post_on_account = Account.objects.get(pk=post_on_account_id)
			
			if transaction.on_account.id == int(post_on_account_id):
				amount_diff_i = post_amount - transaction.amount
				transaction_on_account.increase(amount_diff_i, post_currency)
				post_on_account.increase(amount_diff_i, post_currency)
		
			else:
				transaction_on_account.decrease(transaction.amount, transaction.currency)
				post_on_account.increase(post_amount, post_currency)
				
		else:
			if transaction.on_account:
				transaction_on_account = Account.objects.get(pk=transaction.on_account.id)
				transaction_on_account.decrease(transaction.amount, transaction.currency)
			
			if request.POST.get('on_account'):
				post_on_account = Account.objects.get(pk=request.POST.get('on_account'))
				post_on_account.increase(post_amount, post_currency)
				
				
		if transaction.from_account:
			transaction_from_account.save()
			
		if transaction.on_account:
			transaction_on_account.save()
			
		if request.POST.get('from_account'):
			post_from_account.save()
			
		if request.POST.get('on_account'):
			post_on_account.save()
			
		return super().post(request, *args, **kwargs)
		
	
class TransactionDeleteView(generic.DeleteView):
	model = Transaction
	template_name = 'finance/transaction/transaction_confirm_delete.html'
	success_url = reverse_lazy('finance:transactions_list')
	
	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		transaction = Transaction.objects.get(pk=self.object.pk)
		if transaction.from_account:
			ai = Account.objects.get(pk=transaction.from_account.id)
			ai.increase(transaction.amount, transaction.currency)
			ai.save()
		if transaction.on_account:
			ad = Account.objects.get(pk=transaction.on_account.id)
			ad.decrease(transaction.amount, transaction.currency)
			ad.save()
		return super().post(request, *args, **kwargs)
	
#Accounts views	
	
class AccountsListView(generic.ListView):
	model = Account
	template_name = 'finance/account/accounts_list.html'
	
class AccountDetailView(generic.DetailView):
	model = Account
	template_name = 'finance/account/account_detail.html'
	
class AccountCreateView(generic.CreateView):
	model = Account
	fields = '__all__'
	template_name = 'finance/account/account_create.html'
	
class AccountEditView(generic.UpdateView):
	model = Account
	fields = '__all__'
	template_name = 'finance/account/account_edit.html'
	
class AccountDeleteView(generic.DeleteView):
	model = Account
	template_name = 'finance/account/account_confirm_delete.html'
	success_url = reverse_lazy('finance:accounts_list')
	
#Currencies views

class CurrenciesListView(generic.ListView):
	model = Currency
	template_name = 'finance/currency/currencies_list.html'
	
class CurrencyCreateView(generic.CreateView):
	model = Currency
	fields = '__all__'
	template_name = 'finance/currency/currency_create.html'
	success_url = reverse_lazy('finance:currencies_list')
	
class CurrencyEditView(generic.UpdateView):
	model = Currency
	fields = '__all__'
	template_name = 'finance/currency/currency_edit.html'
	success_url = reverse_lazy('finance:currencies_list')
	
class CurrencyDeleteView(generic.DeleteView):
	model = Currency
	template_name = 'finance/currency/currency_confirm_delete.html'
	success_url = reverse_lazy('finance:currencies_list')
	
#Types views

class TypesListView(generic.ListView):
	model = Type
	template_name = 'finance/type/types_list.html'
	
class TypeCreateView(generic.CreateView):
	model = Type
	fields = '__all__'
	template_name = 'finance/type/type_create.html'
	success_url = reverse_lazy('finance:types_list')
	
class TypeEditView(generic.UpdateView):
	model = Type
	fields = '__all__'
	template_name = 'finance/type/type_edit.html'
	success_url = reverse_lazy('finance:types_list')
	
class TypeDeleteView(generic.DeleteView):
	model = Type
	template_name = 'finance/type/type_confirm_delete.html'
	success_url = reverse_lazy('finance:types_list')	
	
#Categories views

class CategoriesListView(generic.ListView):
	model = Category
	template_name = 'finance/category/categories_list.html'
	
class CategoryCreateView(generic.CreateView):
	model = Category
	fields = '__all__'
	template_name = 'finance/category/category_create.html'
	success_url = reverse_lazy('finance:categories_list')
	
class CategoryEditView(generic.UpdateView):
	model = Category
	fields = '__all__'
	template_name = 'finance/category/category_edit.html'
	success_url = reverse_lazy('finance:categories_list')
	
class CategoryDeleteView(generic.DeleteView):
	model = Category
	template_name = 'finance/category/category_confirm_delete.html'
	success_url = reverse_lazy('finance:categories_list')
	
#Subcategories views

class SubcategoriesListView(generic.ListView):
	model = Subcategory
	template_name = 'finance/subcategory/subcategories_list.html'
	
class SubcategoryCreateView(generic.CreateView):
	model = Subcategory
	fields = '__all__'
	template_name = 'finance/subcategory/subcategory_create.html'
	success_url = reverse_lazy('finance:subcategories_list')
	
class SubcategoryEditView(generic.UpdateView):
	model = Subcategory
	fields = '__all__'
	template_name = 'finance/subcategory/subcategory_edit.html'
	success_url = reverse_lazy('finance:subcategories_list')
	
class SubcategoryDeleteView(generic.DeleteView):
	model = Subcategory
	template_name = 'finance/subcategory/subcategory_confirm_delete.html'
	success_url = reverse_lazy('finance:subcategories_list')
	
#Places views

class PlacesListView(generic.ListView):
	model = Place
	template_name = 'finance/place/places_list.html'
	
class PlaceCreateView(generic.CreateView):
	model = Place
	fields = '__all__'
	template_name = 'finance/place/place_create.html'

finance/templates/finance/transaction/transaction_archive.html
{% extends 'finance/base.html' %}

{% block meta_title %} Список трансакцій {% endblock meta_title %}
{% block title_page %} Список трансакцій {% endblock title_page %}

{% block content %} 
{% if latest %}
<table>
  <thead>
	<tr>
	  <td>&#35;</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
  {% for transaction in latest %}
	<tr>
	  <td>{{ forloop.counter}}</td>
	  <td>{{ transaction.amount }}</td>
	  <td>{{ transaction.currency }}</td>
	  <td>{{ transaction.trans_type }}</td>
	  <td>{{ transaction.category }}</td>
	  <td>{{ transaction.subcategory }}</td>
	  <td>{{ transaction.from_account }}</td>
	  <td>{{ transaction.on_account}}</td>
	  <td>{{ transaction.create_datetime }}</td>
	  <td>{{ transaction.place }}</td>
	  <td>{{ transaction.notes }}</td>
	</tr>
  {% endfor %}
  </tbody>
	
</table>
{% else %}
  <p>Трансакцій не знайдено.</p>
{% endif %}

{% for year in date_list %}
<ul>
  <li><a href="{% url 'finance:archive_year' year.year %}">{{ year|date:'Y' }}</a></li>
</ul>

{% endfor %}

{% endblock content %}

finance/templates/finance/transaction/transaction_archive_day.html
{% extends 'finance/base.html' %}

{% block meta_title %} Список трансакцій за день {% endblock meta_title %}
{% block title_page %} Список трансакцій за {{ day|date:'j E Y' }} року {% endblock title_page %}

{% block content %} 
{% if object_list %}
<table>
  <thead>
	<tr>
	  <td>&#35;</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
  {% for transaction in object_list %}
	<tr>
	  <td>{{ forloop.counter}}</td>
	  <td>{{ transaction.amount }}</td>
	  <td>{{ transaction.currency }}</td>
	  <td>{{ transaction.trans_type }}</td>
	  <td>{{ transaction.category }}</td>
	  <td>{{ transaction.subcategory }}</td>
	  <td>{{ transaction.from_account }}</td>
	  <td>{{ transaction.on_account}}</td>
	  <td>{{ transaction.create_datetime }}</td>
	  <td>{{ transaction.place }}</td>
	  <td>{{ transaction.notes }}</td>
	</tr>
  {% endfor %}
  </tbody>
	
</table>
{% else %}
  <p>Трансакцій не знайдено.</p>
{% endif %}


{% endblock content %}

finance/templates/finance/transaction/transaction_archive_month.html
{% extends 'finance/base.html' %}

{% block meta_title %} Список трансакцій за місяць {% endblock meta_title %}
{% block title_page %} Список трансакцій за {{ month|date:'F' }} місяць {{ month|date:'Y'}} року {% endblock title_page %}

{% block content %} 
{% if object_list %}
<table>
  <thead>
	<tr>
	  <td>&#35;</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
  {% for transaction in object_list %}
	<tr>
	  <td>{{ forloop.counter}}</td>
	  <td>{{ transaction.amount }}</td>
	  <td>{{ transaction.currency }}</td>
	  <td>{{ transaction.trans_type }}</td>
	  <td>{{ transaction.category }}</td>
	  <td>{{ transaction.subcategory }}</td>
	  <td>{{ transaction.from_account }}</td>
	  <td>{{ transaction.on_account}}</td>
	  <td>{{ transaction.create_datetime }}</td>
	  <td>{{ transaction.place }}</td>
	  <td>{{ transaction.notes }}</td>
	</tr>
  {% endfor %}
  </tbody>
	
</table>
{% else %}
  <p>Трансакцій не знайдено.</p>
{% endif %}

{% for day in date_list %}
<ul>
  <li><a href="{% url 'finance:archive_day' day.year day|date:'m' day|date:'d' %}">{{ day|date:'j E Y' }}</a></li>
</ul>
{% endfor %}
{% endblock content %}

finance/templates/finance/transaction/transaction_archive_year.html
{% extends 'finance/base.html' %}

{% block meta_title %} Список трансакцій за рік {% endblock meta_title %}
{% block title_page %} Список трансакцій за {{ year|date:'Y' }} рік {% endblock title_page %}

{% block content %} 
{% if object_list %}
<table>
  <thead>
	<tr>
	  <td>&#35;</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
  {% for transaction in object_list %}
	<tr>
	  <td>{{ forloop.counter}}</td>
	  <td>{{ transaction.amount }}</td>
	  <td>{{ transaction.currency }}</td>
	  <td>{{ transaction.trans_type }}</td>
	  <td>{{ transaction.category }}</td>
	  <td>{{ transaction.subcategory }}</td>
	  <td>{{ transaction.from_account }}</td>
	  <td>{{ transaction.on_account}}</td>
	  <td>{{ transaction.create_datetime }}</td>
	  <td>{{ transaction.place }}</td>
	  <td>{{ transaction.notes }}</td>
	</tr>
  {% endfor %}
  </tbody>
	
</table>
{% else %}
  <p>Трансакцій не знайдено.</p>
{% endif %}

{% for month in date_list %}
<ul>
  <li><a href="{% url 'finance:archive_month' month.year month|date:'m' %}">{{ month|date:'N' }}</a></li>
</ul>

{% endfor %}

{% endblock content %}

finance/templates/finance/transaction/transaction_confirm_delete.html
{% extends 'finance/base.html' %}

{% block meta_title %} Видалити трансакцію {% endblock meta_title %}
{% block title_page %} Видалити трансакцію № {{ object.id }} {% endblock title_page %}

{% block content %} 
<form action="" method="POST">
{% csrf_token %}
  <p>Ви дійсно бажаєте видалити трансакцію?</p>
  <input type="submit" name="submit" value="Видалити">

</form>

{% endblock content %}

finance/templates/finance/transaction/transaction_create.html
{% extends 'finance/base.html' %}

{% block meta_title %} Створити трансакцію {% endblock meta_title %}
{% block title_page %} Створити трансакцію {% endblock title_page %}

{% block content %} 
<form action="" method="POST">
{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="Створити">

</form>

{% endblock content %}

finance/templates/finance/transaction/transaction_detail.html
{% extends 'finance/base.html' %}

{% block meta_title %} Трансакція {% endblock meta_title %}
{% block title_page %} Трансакція № {{ object.id }} {% endblock title_page %}

{% block content %} 
<table>
  <thead>
	<tr>
	  <td>id Трансакції</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
	<tr>
	  <td>{{ object.id }}</td>
	  <td>{{ object.amount }}</td>
	  <td>{{ object.currency }}</td>
	  <td>{{ object.trans_type }}</td>
	  <td>{{ object.category }}</td>
	  <td>{{ object.subcategory }}</td>
	  <td>{{ object.from_account }}</td>
	  <td>{{ object.on_account}}</td>
	  <td>{{ object.create_datetime }}</td>
	  <td>{{ object.place }}</td>
	  <td>{{ object.notes }}</td>
	</tr>
  </tbody>
	
</table>

{% endblock content %}

finance/templates/finance/transaction/transaction_edit.html
{% extends 'finance/base.html' %}

{% block meta_title %} Редагувати трансакцію {% endblock meta_title %}
{% block title_page %} Редагувати трансакцію № {{ object.id }} {% endblock title_page %}

{% block content %} 
<form action="" method="POST">
{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="submit" value="Зберегти">

</form>

{% endblock content %}

finance/templates/finance/transaction/transactions_list.html
{% extends 'finance/base.html' %}

{% block meta_title %} Список трансакцій {% endblock meta_title %}
{% block title_page %} Список трансакцій {% endblock title_page %}

{% block content %} 
{% if object_list %}
<table>
  <thead>
	<tr>
	  <td>&#35;</td>
	  <td>Сума</td>
	  <td>Валюта</td>
	  <td>Тип</td>
	  <td>Категорія</td>
	  <td>Підкатегорія</td>
	  <td>З рахунку</td>
	  <td>На рахунок</td>
	  <td>Дата створення</td>
	  <td>Місце здійснення</td>
	  <td>Примітки</td>
	</tr>
  </thead>
	  
  <tbody>
  {% for transaction in object_list %}
	<tr>
	  <td>{{ forloop.counter}}</td>
	  <td>{{ transaction.amount }}</td>
	  <td>{{ transaction.currency }}</td>
	  <td>{{ transaction.trans_type }}</td>
	  <td>{{ transaction.category }}</td>
	  <td>{{ transaction.subcategory }}</td>
	  <td>{{ transaction.from_account }}</td>
	  <td>{{ transaction.on_account}}</td>
	  <td>{{ transaction.create_datetime }}</td>
	  <td>{{ transaction.place }}</td>
	  <td>{{ transaction.notes }}</td>
	</tr>
  {% endfor %}
  </tbody>
	
</table>
{% else %}
  <p>Трансакцій не знайдено.</p>
{% endif %}

{% endblock content %}